### PR TITLE
Fix SLEIGH rebuilds

### PR DESCRIPTION
**Pull request by artemdinaburg**
Avoid generating a `"FALSE"` in the auto-generated cmake, which would make rebuilds fail.

### CODE REVIEW

**Review by ekilmer — APPROVED** [review]
Huh. I thought CMake would handle this correctly but I guess not. Apologies!

LGTM

**Review by ekilmer — CHANGES_REQUESTED** [review]
Oh! This is actually because this variable is an `option`, so it defaults to `FALSE`... it should really just be a normal `CACHE` variable. I'll make those changes and let you test again.

**Review by ekilmer — COMMENTED** [review]
@artemdinaburg can you please check if the change I made works for you

**Review by ekilmer — APPROVED** [review]

**Review by tetsuo-cpp — APPROVED** [review]

**Comment by artemdinaburg** [comment]
The update is failing rebuilds for me :(.

**Comment by ekilmer** [comment]
Confirmed fixed after using new build directory. Merging now

**Pull request merged**
