### PR TITLE
Regenerate patches from real Git branch

### PR DESCRIPTION
**Pull request by ekilmer**
I'm hoping that keeping real git branches to generate these patch files will make managing future larger patches easier.

See the Ghidra fork wiki page for more details on branching strategy https://github.com/trail-of-forks/ghidra/wiki#sleigh

### CODE REVIEW

**Comment by ekilmer** [comment]
@tetsuo-cpp I tagged you in case you have any questions, comments, concerns.

I did this in prep for recently opened issue #139. Having persistent git branches could also make testing future changes more straightforward with this repo. You can do

```bash
git clone https://github.com/lifting-bits/sleigh
git clone https://github.com/trail-of-forks/ghidra -b sleigh-HEAD-rebasing
cmake -B build-sleigh-HEAD -S sleigh \
    -Dsleigh_RELEASE_TYPE=HEAD \
    -Dsleigh_DEVELOPER_MODE=ON \
    -DFETCHCONTENT_SOURCE_DIR_GHIDRASOURCE=./ghidra
cd build-sleigh-HEAD && ctest -V
```
And then commit and push whatever changes you have to the Ghidra fork branch, regenerate the patches, and commit the new/changed patches to this repo.

**Comment by tetsuo-cpp** [comment]
> @tetsuo-cpp I tagged you in case you have any questions, comments, concerns.
> 
> I did this in prep for recently opened issue #139. Having persistent git branches could also make testing future changes more straightforward with this repo. You can do
> 
> ```shell
> git clone https://github.com/lifting-bits/sleigh
> git clone https://github.com/trail-of-forks/ghidra -b sleigh-HEAD-rebasing
> cmake -B build-sleigh-HEAD -S sleigh \
>     -Dsleigh_RELEASE_TYPE=HEAD \
>     -Dsleigh_DEVELOPER_MODE=ON \
>     -DFETCHCONTENT_SOURCE_DIR_GHIDRASOURCE=./ghidra
> cd build-sleigh-HEAD && ctest -V
> ```
> 
> And then commit and push whatever changes you have to the Ghidra fork branch, regenerate the patches, and commit the new/changed patches to this repo.

Cool! So we just need to do this whenever stable or HEAD get to the point where some of our patches are failing to apply right?

**Review by tetsuo-cpp — APPROVED** [review]
LGTM!

**Comment by pgoodman** [comment]
Ping @ekilmer

**Comment by ekilmer** [comment]
closing this because #143 includes these changes

**Pull request closed without merging**
