### PR TITLE
Patch to remove 'using namespace std' from headers

### LINKED ISSUE #139: Headers are getting polluted by `using namespace std`
The ghidra source code is riddled with `using namespace std` in various header files. This is bad practice and it would be nice if this could be patched away. It causes all kinds of confusing issues (one notable one being with `std::byte` and `byte` from some Windows COM headers).

Ideally these occurrences would be patched out, but obviously the cost is high because you'd have to maintain an extensive test set...

### PR DESCRIPTION
**Pull request by ekilmer**
closes #139

### CODE REVIEW

**Comment by mrexodia** [comment]
My intention was to try this patch with remill (since that's where I first ran into the issue), but it looks like there are some additional patches there that break with this branch. I managed to fix the ArmThumb patch from remill and the only issue I ran into was that `register` is no longer supported in C++17. [This patch](https://github.com/lifting-bits/sleigh/compare/remove-using-namespace-std-from-headers...mrexodia:sleigh:remove-using-namespace-std-from-headers) seems to fix that.

Unfortunately now I run into a linker error from remill (which I think related to the fact that remill is on a different version this repo and the API changed?):

```
[100%] Linking CXX executable remill-lift-15
Undefined symbols for architecture arm64:
  "ContextInternal::restoreFromSpec(Element const*, AddrSpaceManager const*)", referenced from:
      remill::sleigh::SingleInstructionSleighContext::restoreEngineFromStorage() in libremill_arch_sleigh.a(Arch.cpp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ekilmer** [comment]
> My intention was to try this patch with remill (since that's where I first ran into the issue), but it looks like there are some additional patches there that break with this branch. I managed to fix the ArmThumb patch from remill and the only issue I ran into was that `register` is no longer supported in C++17. [This patch](https://github.com/lifting-bits/sleigh/compare/remove-using-namespace-std-from-headers...mrexodia:sleigh:remove-using-namespace-std-from-headers) seems to fix that.
> 
> Unfortunately now I run into a linker error from remill (which I think related to the fact that remill is on a different version this repo and the API changed?):
> 
> ```
> [100%] Linking CXX executable remill-lift-15
> Undefined symbols for architecture arm64:
>   "ContextInternal::restoreFromSpec(Element const*, AddrSpaceManager const*)", referenced from:
>       remill::sleigh::SingleInstructionSleighContext::restoreEngineFromStorage() in libremill_arch_sleigh.a(Arch.cpp.o)
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> Here is my current WIP repo if you want to try: https://github.com/mrexodia/remill/tree/sleigh-using-namespace


Ah. Yeah, this patch is for the latest Ghidra 10.2 version, which has some internal sleigh API changes, and remill has not been updated yet. Remill also has some additional patches, which I have not looked into yet and seem to require updating, as you've found out.

I won't have time to look into this too much this week, but I will take a look when I am back.

There are a few places I will start to look based on updating to Ghidra 10.2 in other tools:
* https://github.com/lifting-bits/sleigh/commit/f38eee41a289ac5fbf27c6951a3c65e8a48e7bac#diff-aed2f30b604fcd3c832b0255d6cd0ef5a7cca4cab0d8d2c77ee6d125d2fcf301
* https://github.com/trailofbits/maat/pull/160/files#diff-7e5860b8ac02e6dc2650d19d18a9e3fb9ab939518a85d7b0f99dd67fca124216 (although these tests are failing for some reason now 🤔)
* https://github.com/trailofbits/mishegos/pull/1462/files#diff-a0f9b268e448e17e90e505165fe08069883b1e3b5d0c7cac92065f501f923722 (to a lesser extent)

**Comment by mrexodia** [comment]
Thanks, I'll take a look to see if a lot of effort is required to update remill to the latest Ghidra version!

**Comment by pgoodman** [comment]
Ping @ekilmer

**Comment by mrexodia** [comment]
Any chance this could be merged? I tested and this does fix the issue. It's a blocker for building remill on Windows and also a blocker for https://github.com/trailofbits/maat/pull/97

**Review by tetsuo-cpp — APPROVED** [review]
LGTM from my point of view.

**Comment by ekilmer** [comment]
Updated the patches for the latest commit on Ghidra's `master` branch. I assume that if things are compiling correctly and passing tests, then it works for you as well @mrexodia.

Would you be willing to write a test (or post some C++ code that I can integrate into CMake) that we could include in this repo to make sure we don't suffer regressions?

**Pull request merged**
